name: Create Wazuh wui package
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New Version'
        required: true
      username:
        description: 'Username'
        required: true
      password:
        description: 'Password'
        required: true        
      email:
        description: 'Email'
        required: true        

jobs:
  create_wazuh_wui_package:
    runs-on: ubuntu-18.04
    steps:
      - name: Step 01 - Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '10.24.1'
      - name: Step 02 - Checkout current project 
        uses: actions/checkout@v2
      - name: Step 03 - Login to NPM
        run: |
         echo "New Version ${{ github.event.inputs.new_version }}"
         echo "username ${{ github.event.inputs.username }}"
         echo "password ${{ github.event.inputs.password }}"
         echo "email ${{ github.event.inputs.email }}"
